### PR TITLE
EnrollmentId

### PR DESCRIPTION
**Pull request by matthias-geuchen**
### Reason for this PR
- according to the new API specification, MatriculationData on chain is pseudonymized by an enrollmentId

### Changes in this PR
- Replace matriculationId, firstName, lastName, and birthdate by enrollmentId

### CODE REVIEW

**Review by NikoBergemann — APPROVED** [review]
[https://github.com/upb-uc4/hlf-api/actions/runs/268802728](https://github.com/upb-uc4/hlf-api/actions/runs/268802728)

seems to work

**Review by sluis1 — APPROVED** [review]
in relation to the passed tests, it looks good for me.

**Review by mco33415 — APPROVED** [review]
Seems fine to me.

**Comment by NikoBergemann** [comment]
Removed @nklsd review on his behalf and with agreement since we all worked on this together anyways

**Pull request merged**
