### PR TITLE
Feature/private data

### PR DESCRIPTION
**Pull request by matthias-geuchen**
### Reason for this PR
- sensitive information must be deletable and shall thus not be stored on the chain in plaintext

### Changes in this PR
- move transaction parameters holding sensitive data to transient fields

### CODE REVIEW

**Review by mco33415 — APPROVED** [review]
Seems fine, if the tests work.

**Review by sluis1 — APPROVED** [review]
looks good:)

**Review by mco33415 — APPROVED** [review]
Sorry :)

**Review by nklsd — APPROVED** [review]
looks good, can be merged

**Pull request merged**
